namespace InfernumMode.Content.BossBars
{
    public enum VanillaBosses
    {
        EyeOfCthulhu = 0,
        EaterOfWorlds = 1,
        BrainOfCthulhu = 2,
        Skeletron = 3,
        QueenBee = 4,
        KingSlime = 5,
        WallOfFlesh = 6,
        Twins = 7,
        Destroyer = 8,
        Prime = 9,
        Plantera = 10,
        Golem = 11,
        Fishron = 12,
        Cultist = 13,
        Moonlord = 14,
        MartianSaucer = 15,
        FlyingDutchman = 16,
        MourningWood = 17,
        Pumpking = 18,
        IceQueen = 19,
        Everscream = 20,
        Santank = 21,
        DarkMage = 22,
        Ogre = 23,
        Betsy = 24,
        EmpressOfLight = 25,
        QueenSlime = 26,
        Deerclops = 27
    }

    public enum CalamityBosses
    {
        DesertScourge = 0,
        GiantClam = 1,
        Crabulon = 2,
        HiveMind = 3,
        Perforator = 4,
        SlimeGod = 5,
        Cryogen = 6,
        AquaticScourge = 7,
        BrimstoneElemental = 8,
        CalamitasShadow = 9,
        GreatSandShark = 10,
        Anahita = 11,
        Aureus = 12,
        PlaguebringerGoliath = 13,
        Ravager = 14,
        Deus = 15,
        Guardians = 16,
        Dragonfolly = 17,
        Providence = 18,
        CeaselessVoid = 19,
        StormWeaver = 20,
        Signus = 21,
        Polterghast = 22,
        OldDuke = 23,
        DoG = 24,
        AEW = 25,
        Draedon = 26,
        SCal = 27
    }
}
